import { MembershipAdmin } from './Memberships';
import { useEffect, useState } from 'react';
import { Check, Eye, Plus, Save, Trash2 } from 'lucide-react';
import { api } from '../api';
import { useApp } from '../App';
import { useAction, useApi } from '../hooks';
import { Blocks, Empty, Heading, Loading, Notice } from '../ui';
import type { Block, Brand, Trainer } from '../types';
import { experiences, specializations } from './Trainers';

export function Admin() {
  const [tab, setTab] = useState('brand');
  return <><Heading eyebrow="ПРОСТРАНСТВО ВАШЕГО БРЕНДА" title="Управление клубом" /><div className="tabs" role="tablist">{[{ id: 'brand', label: 'Бренд и страницы' }, { id: 'trainers', label: 'Тренеры' }, { id: 'memberships', label: 'Абонементы и вход' }].map(t => <button role="tab" aria-selected={tab === t.id} key={t.id} className={tab === t.id ? 'active' : ''} onClick={() => setTab(t.id)}>{t.label}</button>)}</div>{tab === 'brand' ? <BrandEditor /> : tab === 'trainers' ? <TrainerAdmin /> : <MembershipAdmin />}</>;
}

function BrandEditor() {
  const { reloadSite } = useApp();
  const source = useApi<{ settings: Brand; version: number }>('/api/admin/site');
  const [draft, setDraft] = useState<Brand>(); const [version, setVersion] = useState(0); const [dirty, setDirty] = useState(false);
  const action = useAction();
  useEffect(() => { if (source.data) { setDraft(source.data.settings); setVersion(source.data.version); setDirty(false); } }, [source.data]);
  const update = (value: Partial<Brand>) => { setDraft(d => ({ ...d!, ...value })); setDirty(true); };
  if (source.loading) return <Loading />;
  if (!draft) return <Notice error={source.error} />;
  return <><Notice error={source.error} /><div className="admin-layout"><form onSubmit={e => { e.preventDefault(); void action.run(async () => {
    const result = await api<{ version: number }>('/api/admin/site', 'PUT', { settings: draft, version }); setVersion(result.version); setDirty(false);
  }, 'Черновик сохранён. Опубликуйте, чтобы посетители увидели изменения.'); }}>
    <section className="card"><h2>Ваш бренд</h2><label>Название клуба<input required maxLength={80} value={draft.name} onChange={e => update({ name: e.target.value })} /></label><label>Заголовок главной<input required maxLength={160} value={draft.tagline} onChange={e => update({ tagline: e.target.value })} /></label><div className="form-grid"><label>Акцентный цвет<div className="color-field"><input type="color" value={draft.accent} onChange={e => update({ accent: e.target.value })} /><code>{draft.accent}</code></div></label><label>Тема по умолчанию<select value={draft.defaultTheme} onChange={e => update({ defaultTheme: e.target.value as Brand['defaultTheme'] })}><option value="dark">Тёмная</option><option value="light">Светлая</option><option value="system">Как на устройстве</option></select></label></div><label>Форма элементов<select value={draft.shape} onChange={e => update({ shape: e.target.value as Brand['shape'] })}><option value="rounded">Скруглённая</option><option value="square">Строгая</option></select></label></section>
    <BlockEditor title="Блоки главной страницы" blocks={draft.homeBlocks} onChange={homeBlocks => update({ homeBlocks })} /><BlockEditor title="Блоки профиля" blocks={draft.profileBlocks} onChange={profileBlocks => update({ profileBlocks })} />
    <Notice {...action} /><div className="form-actions sticky-actions"><button className="secondary" disabled={action.busy}><Save size={17} />Сохранить черновик</button><button className="primary" type="button" disabled={action.busy || dirty || version === 0} onClick={() => action.run(async () => { const result = await api<{ version: number }>('/api/admin/site/publish', 'POST', { version }); setVersion(result.version); await reloadSite(); }, 'Изменения опубликованы на сайте клуба.')}><Check size={17} />Опубликовать</button></div>{dirty && <p className="muted">Есть несохранённые изменения.</p>}
  </form><aside className="preview-column"><span className="eyebrow"><Eye size={15} />ПРЕДПРОСМОТР ЧЕРНОВИКА</span><div className="brand-preview" style={{ '--preview-accent': draft.accent, borderRadius: draft.shape === 'square' ? 0 : 18 } as React.CSSProperties}><strong>{draft.name}</strong><h2>{draft.tagline}</h2><span className="preview-button">Начать тренировку ↗</span></div><Blocks blocks={draft.homeBlocks} /><p className="muted">Предпросмотр главной. Для публикации сначала сохраните черновик. Личная тема пользователя имеет приоритет над темой клуба.</p></aside></div></>;
}

function BlockEditor({ title, blocks, onChange }: { title: string; blocks: Block[]; onChange: (blocks: Block[]) => void }) {
  const edit = (index: number, value: Partial<Block>) => onChange(blocks.map((b, i) => i === index ? { ...b, ...value } : b));
  return <section className="card"><h2>{title}</h2>{blocks.map((block, index) => <div className="block-editor" key={index}><div className="section-heading"><label className="checkbox"><input type="checkbox" checked={block.visible} onChange={e => edit(index, { visible: e.target.checked })} />Показывать блок {index + 1}</label><button type="button" className="icon-button" aria-label={`Удалить блок ${index + 1}`} onClick={() => onChange(blocks.filter((_, i) => i !== index))}><Trash2 size={17} /></button></div><label>Заголовок<input required maxLength={100} value={block.title} onChange={e => edit(index, { title: e.target.value })} /></label><label>Текст<textarea maxLength={1500} value={block.text} onChange={e => edit(index, { text: e.target.value })} /></label><div className="form-actions"><button type="button" className="link-button" disabled={index === 0} onClick={() => { const next = [...blocks]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange(next); }}>Выше</button><button type="button" className="link-button" disabled={index === blocks.length - 1} onClick={() => { const next = [...blocks]; [next[index + 1], next[index]] = [next[index], next[index + 1]]; onChange(next); }}>Ниже</button></div></div>)}<button type="button" className="secondary" disabled={blocks.length >= 12} onClick={() => onChange([...blocks, { title: '', text: '', visible: true }])}><Plus size={17} />Добавить блок</button></section>;
}

function TrainerAdmin() {
  const trainers = useApi<Trainer[]>('/api/admin/trainers');
  const [search, setSearch] = useState(''); const members = useApi<{ id: string; name: string; email?: string; phoneNumber?: string }[]>(`/api/admin/users?search=${encodeURIComponent(search)}`);
  const [userId, setUserId] = useState(''); const [about, setAbout] = useState(''); const [price, setPrice] = useState(1000);
  const [specialization, setSpecialization] = useState('Strength'); const [experience, setExperience] = useState('OneToThreeYears'); const [format, setFormat] = useState('Gym'); const [active, setActive] = useState(true);
  const action = useAction();
  const edit = (trainer: Trainer) => { setUserId(trainer.userId); setAbout(trainer.about ?? ''); setPrice(trainer.pricePerSession); setSpecialization(trainer.specializations); setExperience(trainer.experience); setFormat(trainer.formats); setActive(trainer.isActive); };
  return <div className="admin-layout"><section className="card"><h2>Карточка тренера</h2><p className="muted">Выберите зарегистрированного участника клуба. Его аккаунт будет связан с карточкой тренера.</p><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await api(`/api/admin/trainers/${encodeURIComponent(userId)}`, 'PUT', { specializations: specialization, experience, formats: format, pricePerSession: price, about, isActive: active }); trainers.reload(); }, 'Карточка тренера сохранена'); }}><label>Поиск участника<input placeholder="Имя, email или телефон" value={search} onChange={e => setSearch(e.target.value)} /></label><Notice error={members.error} /><label>Участник<select required value={userId} onChange={e => setUserId(e.target.value)}><option value="">Выберите аккаунт</option>{members.data?.map(m => <option value={m.id} key={m.id}>{m.name} · {m.email || m.phoneNumber}</option>)}</select></label><div className="form-grid"><label>Направление<select value={specialization} onChange={e => setSpecialization(e.target.value)}>{!specializations[specialization] && <option value={specialization}>{specialization}</option>}{Object.entries(specializations).map(([value, title]) => <option key={value} value={value}>{title}</option>)}</select></label><label>Опыт<select value={experience} onChange={e => setExperience(e.target.value)}>{Object.entries(experiences).map(([value, title]) => <option key={value} value={value}>{title}</option>)}</select></label><label>Цена, FitCoins<input type="number" required min={1} max={100000} value={price} onChange={e => setPrice(+e.target.value)} /></label><label>Формат<select value={format} onChange={e => setFormat(e.target.value)}>{!['Gym', 'Online', 'OnSite'].includes(format) && <option value={format}>{format}</option>}<option value="Gym">В зале</option><option value="Online">Онлайн</option><option value="OnSite">С выездом</option></select></label></div><label>О тренере<textarea maxLength={2000} value={about} onChange={e => setAbout(e.target.value)} /></label><label className="checkbox"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} />Показывать в списке тренеров</label><button className="primary" disabled={action.busy || !userId}>Сохранить тренера</button><Notice {...action} /></form></section><section className="card"><h2>Команда клуба</h2><Notice error={trainers.error} />{trainers.loading ? <Loading /> : !trainers.data?.length ? <Empty>Пока нет тренеров</Empty> : trainers.data.map(t => <button className="list-row trainer-admin-row" key={t.id} onClick={() => edit(t)}><span className="avatar">{t.name[0]}</span><span><strong>{t.name}</strong><small>{t.isActive ? 'Опубликован' : 'Скрыт'} · {t.pricePerSession} FC</small></span><span>Изменить</span></button>)}</section></div>;
}
