import { useEffect, useState } from 'react';
import { CreditCard, Plus, ScanLine, Snowflake, Users } from 'lucide-react';
import { api } from '../api';
import { useAction, useApi } from '../hooks';
import { Empty, Heading, Loading, Notice } from '../ui';

type Terms = { name: string; description: string; price: number; currency: string; durationDays: number; durationMonths: number; visitLimit: number | null; dailyVisitLimit: number; freezeDays: number; freezeMonths: number; weekdays: number; timeZone: string; allAreas: boolean; areaIds: string[] };
type Plan = { id: string; terms: Terms; isActive: boolean; version: number };
type Area = { id: string; name: string; isActive: boolean; version: number };
type Pass = { id: string; userId: string; name?: string; terms: Terms; startsAt: string; expiresAt: string; frozenUntil?: string; usedVisits: number; freezeDaysRemaining: number; status: string; version: number };
const states: Record<string,string> = { active: 'Действует', scheduled: 'Ожидает начала', frozen: 'Заморожен', expired: 'Срок истёк', exhausted: 'Посещения закончились', cancelled: 'Отменён' };
const stamp = (s: string) => new Date(s).toLocaleString('ru-RU', { dateStyle: 'short', timeStyle: 'short' });
const freshTerms = (): Terms => ({ name: '', description: '', price: 0, currency: 'RUB', durationDays: 30, durationMonths: 1, visitLimit: null, dailyVisitLimit: 1, freezeDays: 0, freezeMonths: 0, weekdays: 127, timeZone: 'Europe/Moscow', allAreas: true, areaIds: [] });
const localNow = () => { const d = new Date(); return new Date(+d - d.getTimezoneOffset() * 60000).toISOString().slice(0,16); };
const price = (t: Terms) => `${t.price.toLocaleString('ru-RU')} ${t.currency}`;
function TermsSummary({ terms: t, areas }: { terms: Terms; areas: Area[] }) {
  return <><p className="muted">{t.description}</p><div className="membership-facts"><span>{t.durationMonths ? `${t.durationMonths} мес.` : `${t.durationDays} дн.`}</span><span>{t.visitLimit === null ? 'Безлимит' : `${t.visitLimit} посещений`}</span><span>Входов в день: {t.dailyVisitLimit}</span><span>Заморозка: {[t.freezeMonths ? t.freezeMonths + ' мес.' : '', t.freezeDays ? t.freezeDays + ' дн.' : ''].filter(Boolean).join(' + ') || 'не включена'}</span></div><p>{t.allAreas ? 'Все услуги клуба, включая новые' : t.areaIds.map(id => areas.find(a => a.id === id)?.name ?? 'Архивная услуга').join(' · ')}</p><small className="muted">{['Вс','Пн','Вт','Ср','Чт','Пт','Сб'].filter((_,i) => (t.weekdays & (1 << i)) !== 0).join(', ')} · {t.timeZone}</small></>;
}

export function Memberships() {
  const plans = useApi<Plan[]>('/api/memberships/plans'); const mine = useApi<Pass[]>('/api/memberships/mine');
  const areas = useApi<Area[]>('/api/memberships/areas'); const [historyId, setHistory] = useState<string | null>(null);
  return <><Heading eyebrow="ДОСТУП В КЛУБ" title="Мои абонементы" /><Notice error={mine.error || plans.error || areas.error} />
    {mine.loading ? <Loading /> : <div className="membership-grid">{!mine.data?.length && <Empty>Абонементов пока нет. Для оформления обратись на ресепшен клуба.</Empty>}{mine.data?.map(p => <article className="card" key={p.id}><span className={`pass-status ${p.status}`}>{states[p.status]}</span><h2>{p.terms.name}</h2><p>{stamp(p.startsAt)} — {stamp(p.expiresAt)}</p><strong>{p.terms.visitLimit === null ? `Посещений использовано: ${p.usedVisits}` : `Осталось ${Math.max(0,p.terms.visitLimit-p.usedVisits)} из ${p.terms.visitLimit}`}</strong><p>Доступно дней заморозки: {p.freezeDaysRemaining}</p>{p.status === 'frozen' && <p>Заморожен до {stamp(p.frozenUntil!)}</p>}<TermsSummary terms={p.terms} areas={areas.data ?? []} /><button className="secondary" onClick={() => setHistory(p.id)}>История посещений</button></article>)}</div>}
    <Heading eyebrow="ВЫБЕРИ СВОЙ РИТМ" title="Тарифы клуба" /><div className="membership-grid">{plans.data?.map(p => <article className="card" key={p.id}><CreditCard size={25} /><h2>{p.terms.name}</h2><strong className="plan-price">{price(p.terms)}</strong><TermsSummary terms={p.terms} areas={areas.data ?? []} /><p className="muted">Оформление и оплата на ресепшене.</p></article>)}</div>{historyId && <History id={historyId} close={() => setHistory(null)} />}</>;
}
function History({ id, close }: { id: string; close: () => void }) {
  const source = useApi<{id:string;kind:string;createdAt:string;note?:string}[]>(`/api/memberships/${id}/history`);
  const names: Record<string,string> = { issued:'Выдан',visit:'Вход по карте / браслету',freeze:'Заморозка',cancel:'Отмена' };
  return <section className="card"><div className="section-heading"><h2>Последние операции</h2><button className="secondary" onClick={close}>Закрыть историю</button></div><Notice error={source.error} />{source.loading ? <Loading /> : source.data?.map(e => <div className="list-row" key={e.id}><span><strong>{names[e.kind] ?? e.kind}</strong><small>{e.note}</small></span><span>{stamp(e.createdAt)}</span></div>)}</section>;
}

export function MembershipAdmin() {
  const [section, setSection] = useState('plans');
  return <><div className="tabs">{[['plans','Тарифы и услуги'],['members','Выдача и абонементы'],['access','Карты и вход']].map(([id,label]) => <button key={id} className={section === id ? 'active' : ''} onClick={() => setSection(id)}>{label}</button>)}</div>{section === 'plans' ? <PlanEditor /> : section === 'members' ? <PassAdmin /> : <AccessAdmin />}</>;
}
function MemberSelect({ value, onChange }: { value:string; onChange:(id:string)=>void }) {
  const [search,setSearch] = useState(''); const members = useApi<{id:string;name:string;email?:string;phoneNumber?:string}[]>(`/api/admin/users?search=${encodeURIComponent(search)}`);
  return <><label>Поиск участника<input placeholder="Имя, email или телефон" value={search} onChange={e=>setSearch(e.target.value)} /></label><Notice error={members.error} /><label>Участник<select required value={value} onChange={e=>onChange(e.target.value)}><option value="">Выберите участника</option>{members.data?.map(m=><option key={m.id} value={m.id}>{m.name} · {m.email || m.phoneNumber}</option>)}</select></label></>;
}
function PlanEditor() {
  const plans = useApi<Plan[]>('/api/admin/memberships/plans'); const areas = useApi<Area[]>('/api/admin/access/areas');
  const [draft,setDraft] = useState<Plan>({id:crypto.randomUUID(),terms:freshTerms(),isActive:true,version:0});
  const [areaName,setAreaName] = useState(''); const action=useAction(); const areaAction=useAction();
  const t=draft.terms; const update=(v:Partial<Terms>)=>setDraft({...draft,terms:{...t,...v}});
  return <><section className="card"><h2>Услуги и зоны клуба</h2><p className="muted">Например: тренажёрный зал, бассейн, йога, групповые тренировки. Эти услуги выбираются в тарифах и на экране входа.</p><form className="form-actions" onSubmit={e=>{e.preventDefault();void areaAction.run(async()=>{await api(`/api/admin/access/areas/${crypto.randomUUID()}`,'PUT',{name:areaName,isActive:true,version:0});setAreaName('');areas.reload();});}}><label>Название услуги<input required maxLength={80} value={areaName} onChange={e=>setAreaName(e.target.value)} /></label><button className="secondary" disabled={areaAction.busy}><Plus size={16}/>Добавить услугу</button></form><Notice {...areaAction} error={areaAction.error || areas.error}/><div className="membership-facts">{areas.data?.map(a=><button className="secondary" disabled={areaAction.busy} key={a.id} onClick={()=>areaAction.run(async()=>{await api(`/api/admin/access/areas/${a.id}`,'PUT',{name:a.name,isActive:!a.isActive,version:a.version});areas.reload();})}>{a.name} · {a.isActive?'Доступна — скрыть':'Скрыта — включить'}</button>)}</div></section>
  <div className="admin-layout"><section className="card"><div className="section-heading"><h2>{draft.version ? 'Редактирование тарифа' : 'Новый тариф'}</h2><button className="secondary" onClick={()=>setDraft({id:crypto.randomUUID(),terms:freshTerms(),isActive:true,version:0})}>Новый</button></div><p className="muted">Изменения действуют на новые выдачи. У уже выданных абонементов сохраняются цена и условия.</p><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api(`/api/admin/memberships/plans/${draft.id}`,'PUT',draft);plans.reload();setDraft({id:crypto.randomUUID(),terms:freshTerms(),isActive:true,version:0});},'Тариф сохранён');}}>
  <label>Название тарифа<input required maxLength={80} value={t.name} onChange={e=>update({name:e.target.value})}/></label><label>Описание<textarea maxLength={1500} value={t.description} onChange={e=>update({description:e.target.value})}/></label><div className="form-grid"><label>Цена<input type="number" required min={0} max={10000000} step="0.01" value={t.price} onChange={e=>update({price:+e.target.value})}/></label><label>Валюта<select value={t.currency} onChange={e=>update({currency:e.target.value})}>{['RUB','KZT','BYN','EUR','USD'].map(x=><option key={x}>{x}</option>)}</select></label><label>Единица срока<select value={t.durationMonths?'months':'days'} onChange={e=>update({durationMonths:e.target.value==='months'?1:0})}><option value="months">Календарные месяцы</option><option value="days">Дни</option></select></label><label>Срок действия<input type="number" min={1} max={t.durationMonths?36:1095} required value={t.durationMonths || t.durationDays} onChange={e=>update(t.durationMonths?{durationMonths:+e.target.value}:{durationDays:+e.target.value})}/></label></div>
  <label className="checkbox"><input type="checkbox" checked={t.visitLimit===null} onChange={e=>update({visitLimit:e.target.checked?null:8})}/>Безлимит посещений</label>{t.visitLimit!==null && <label>Количество посещений<input type="number" min={1} max={10000} required value={t.visitLimit} onChange={e=>update({visitLimit:+e.target.value})}/></label>}<label>Максимум входов за день<input type="number" min={1} max={100} required value={t.dailyVisitLimit} onChange={e=>update({dailyVisitLimit:+e.target.value})}/></label>
  <div className="form-grid"><label>Заморозка: месяцы<input type="number" min={0} max={12} required value={t.freezeMonths} onChange={e=>update({freezeMonths:+e.target.value})}/></label><label>Дополнительные дни заморозки<input type="number" min={0} max={365} required value={t.freezeDays} onChange={e=>update({freezeDays:+e.target.value})}/></label></div><p className="muted">Месяцы заморозки переводятся в дни по календарю от даты начала абонемента. Заморозку можно использовать частями; срок продлевается на её длительность.</p>
  <fieldset className="goals"><legend>Доступные услуги</legend><label className="checkbox"><input type="checkbox" checked={t.allAreas} onChange={e=>update({allAreas:e.target.checked})}/>Все услуги, включая добавленные в будущем</label>{!t.allAreas && areas.data?.filter(a=>a.isActive || t.areaIds.includes(a.id)).map(a=><label className="checkbox" key={a.id}><input type="checkbox" checked={t.areaIds.includes(a.id)} onChange={e=>update({areaIds:e.target.checked?[...t.areaIds,a.id]:t.areaIds.filter(id=>id!==a.id)})}/>{a.name}{!a.isActive?' (скрыта)':''}</label>)}</fieldset>
  <fieldset className="goals"><legend>Дни доступа</legend>{['Вс','Пн','Вт','Ср','Чт','Пт','Сб'].map((d,i)=><label key={d} className="checkbox"><input type="checkbox" checked={!!(t.weekdays&(1<<i))} onChange={e=>update({weekdays:e.target.checked?t.weekdays|(1<<i):t.weekdays&~(1<<i)})}/>{d}</label>)}</fieldset><label>Часовой пояс клуба<input required maxLength={100} value={t.timeZone} onChange={e=>update({timeZone:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>Доступен для выдачи и виден участникам</label><button className="primary" disabled={action.busy}>Сохранить тариф</button><Notice {...action}/></form></section>
  <section className="card"><h2>Тарифы клуба</h2><Notice error={plans.error}/>{plans.loading?<Loading/>:!plans.data?.length?<Empty>Создайте первый тариф</Empty>:plans.data.map(p=><button key={p.id} className="list-row trainer-admin-row" onClick={()=>setDraft(p)}><span><strong>{p.terms.name}</strong><small>{price(p.terms)} · {p.isActive?'Доступен':'Скрыт'}</small></span><span>Изменить</span></button>)}</section></div></>;
}

function PassAdmin() {
  const [userId,setUser] = useState(''); const [page,setPage]=useState(1); const [planId,setPlan]=useState(''); const [startsAt,setStart]=useState(localNow); const [note,setNote]=useState('');
  const plans=useApi<Plan[]>('/api/admin/memberships/plans'); const passes=useApi<Pass[]>(`/api/admin/memberships?page=${page}${userId?'&userId='+encodeURIComponent(userId):''}`);
  const [command,setCommand]=useState<{pass:Pass;kind:string}|null>(null); const [days,setDays]=useState(1); const [reason,setReason]=useState(''); const [history,setHistory]=useState<string|null>(null);
  const action=useAction(); const [issueId,setIssueId]=useState(()=>crypto.randomUUID());
  return <><section className="card"><h2>Выдать абонемент</h2><p className="muted">Выдача не списывает деньги. Укажите основание: оплата на ресепшене, подарок или другое решение клуба.</p><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api('/api/admin/memberships','POST',{id:issueId,planId,userId,startsAt:new Date(startsAt).toISOString(),note});setIssueId(crypto.randomUUID());passes.reload();},'Абонемент выдан');}}><MemberSelect value={userId} onChange={id=>{setUser(id);setPage(1);setIssueId(crypto.randomUUID());}}/><div className="form-grid"><label>Тариф<select required value={planId} onChange={e=>setPlan(e.target.value)}><option value="">Выберите тариф</option>{plans.data?.filter(p=>p.isActive).map(p=><option key={p.id} value={p.id}>{p.terms.name} · {price(p.terms)}</option>)}</select></label><label>Начало действия<input type="datetime-local" required value={startsAt} onChange={e=>setStart(e.target.value)}/></label></div><label>Основание выдачи<input required maxLength={500} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={action.busy}>Выдать абонемент</button></form><Notice {...action} error={action.error || plans.error}/></section>
  <section className="card"><h2>{userId?'Абонементы участника':'Все абонементы'}</h2><Notice error={passes.error}/>{passes.loading?<Loading/>:!passes.data?.length?<Empty>Абонементов пока нет</Empty>:passes.data.map(p=><article className="membership-row" key={p.id}><div><span className={`pass-status ${p.status}`}>{states[p.status]}</span><h3>{p.name} · {p.terms.name}</h3><p>{stamp(p.startsAt)} — {stamp(p.expiresAt)}</p><p>Посещения: {p.usedVisits} / {p.terms.visitLimit??'∞'} · Дней заморозки осталось: {p.freezeDaysRemaining}</p></div><div className="form-actions"><button className="secondary" onClick={()=>setHistory(p.id)}>История</button><button className="secondary" disabled={p.status!=='active' || p.freezeDaysRemaining<1} onClick={()=>{setCommand({pass:p,kind:'freeze'});setReason('');setDays(1);}}><Snowflake size={16}/>Заморозить</button><button className="secondary" disabled={p.status==='cancelled'} onClick={()=>{setCommand({pass:p,kind:'cancel'});setReason('');}}>Отменить</button></div></article>)}<div className="pagination"><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>Назад</button><span>{page}</span><button className="secondary" disabled={(passes.data?.length??0)<50} onClick={()=>setPage(page+1)}>Далее</button></div></section>
  {command && <section className="card"><h2>{command.kind==='freeze'?'Заморозить':'Отменить'}: {command.pass.terms.name}</h2><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api(`/api/admin/memberships/${command.pass.id}/${command.kind}`,'POST',{operationId:crypto.randomUUID(),version:command.pass.version,days,note:reason});setCommand(null);passes.reload();},'Изменения сохранены');}}>{command.kind==='freeze'?<label>Дней заморозки<input required type="number" min={1} max={Math.min(365,command.pass.freezeDaysRemaining)} value={days} onChange={e=>setDays(+e.target.value)}/></label>:<p>Доступ по этому абонементу прекратится. Возврат денег оформляется отдельно.</p>}<label>Причина<input required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><div className="form-actions"><button className="primary" disabled={action.busy}>Подтвердить</button><button type="button" className="secondary" onClick={()=>setCommand(null)}>Назад</button></div><Notice error={action.error}/></form></section>}{history && <History id={history} close={()=>setHistory(null)}/>}</>;
}

type Person = {id:string;name:string;areaName:string;enteredAt:string;version:number};
function AccessAdmin() {
  const [userId,setUser]=useState(''); const [cardCode,setCardCode]=useState(''); const [label,setLabel]=useState('');
  const cards=useApi<{id:string;label:string;isActive:boolean}[]>(userId?`/api/admin/access/cards?userId=${encodeURIComponent(userId)}`:null);
  const areas=useApi<Area[]>('/api/admin/access/areas'); const presence=useApi<{count:number;people:Person[]}>('/api/admin/access/presence');
  const [scanId,setScanId]=useState(()=>crypto.randomUUID()); const [code,setCode]=useState(''); const [areaId,setArea]=useState(''); const [exit,setExit]=useState(false); const [scanMessage,setScanMessage]=useState('');
  const [close,setClose]=useState<Person|null>(null); const [closeNote,setCloseNote]=useState(''); const action=useAction(); const scan=useAction();
  useEffect(()=>{const timer=setInterval(presence.reload,15000);return()=>clearInterval(timer);},[presence.reload]);
  return <><div className="admin-layout"><section className="card scan-card"><ScanLine size={28}/><h2>Вход по карте / браслету</h2><p className="muted">Выберите услугу и направление, установите курсор в поле кода и приложите карту к USB-считывателю. Ввод завершается Enter.</p><form onSubmit={e=>{e.preventDefault();setScanMessage('');void scan.run(async()=>{const r=await api<{message:string}>('/api/admin/access/scan','POST',{operationId:scanId,code,areaId,exit});setScanMessage(r.message);setCode('');setScanId(crypto.randomUUID());presence.reload();});}}><label>Направление<select value={exit?'exit':'enter'} onChange={e=>{setExit(e.target.value==='exit');setScanMessage('');setScanId(crypto.randomUUID());}}><option value="enter">Вход — списать посещение</option><option value="exit">Выход — без списания</option></select></label>{!exit && <label>Услуга<select required value={areaId} onChange={e=>{setArea(e.target.value);setScanId(crypto.randomUUID());}}><option value="">Выберите услугу</option>{areas.data?.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label>Код карты / браслета<input autoComplete="off" required minLength={4} maxLength={128} value={code} onChange={e=>{setCode(e.target.value);setScanId(crypto.randomUUID());}}/></label><button className="primary" disabled={scan.busy}>{exit?'Зарегистрировать выход':'Проверить и зарегистрировать вход'}</button><Notice error={scan.error || areas.error} message={scanMessage}/></form></section>
  <section className="card"><Users size={28}/><h2>Сейчас внутри: {presence.data?.count??'—'}</h2><p className="muted">По зарегистрированным входам и выходам. Обновляется каждые 15 секунд; забытый выход можно закрыть вручную с причиной.</p><Notice error={presence.error}/>{presence.data?.people.map(p=><div className="membership-row" key={p.id}><strong>{p.name}</strong><small>{p.areaName} · с {stamp(p.enteredAt)}</small><button className="secondary" onClick={()=>{setClose(p);setCloseNote('');}}>Отметить выход</button></div>)}</section></div>
  {close && <section className="card"><h2>Исправление выхода: {close.name}</h2><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api(`/api/admin/access/presence/${close.id}/close`,'POST',{version:close.version,note:closeNote});setClose(null);presence.reload();});}}><label>Причина<input required maxLength={500} value={closeNote} onChange={e=>setCloseNote(e.target.value)}/></label><button className="primary" disabled={action.busy}>Подтвердить выход</button><button type="button" className="secondary" onClick={()=>setClose(null)}>Назад</button><Notice error={action.error}/></form></section>}
  <section className="card"><h2>Привязка карт и браслетов</h2><MemberSelect value={userId} onChange={setUser}/><form onSubmit={e=>{e.preventDefault();void action.run(async()=>{await api('/api/admin/access/cards','POST',{userId,code:cardCode,label});setCardCode('');setLabel('');cards.reload();},'Карта привязана');}}><div className="form-grid"><label>Метка карты<input required maxLength={80} placeholder="Основной браслет" value={label} onChange={e=>setLabel(e.target.value)}/></label><label>Считать код для привязки<input autoComplete="off" required minLength={4} maxLength={128} value={cardCode} onChange={e=>setCardCode(e.target.value)}/></label></div><button className="primary" disabled={action.busy || !userId}>Привязать карту</button></form><Notice {...action} error={action.error || cards.error}/>{cards.data?.map(c=><div className="list-row" key={c.id}><span>{c.label} · {c.isActive?'Действует':'Заблокирована'}</span>{c.isActive && <button className="secondary" disabled={action.busy} onClick={()=>{if(window.confirm(`Заблокировать «${c.label}»? Вход по этой карте прекратится.`))void action.run(async()=>{await api(`/api/admin/access/cards/${c.id}/revoke`,'POST');cards.reload();});}}>Заблокировать</button>}</div>)}</section></>;
}
