import { useState } from 'react';
import { CalendarDays, Plus } from 'lucide-react';
import { api } from '../api';
import { useAction, useApi } from '../hooks';
import { date, Empty, Heading, Loading, Notice } from '../ui';
import type { Slot } from './Trainers';

type Incoming = { id: string; message?: string; goal: string; studentUserId: string; createdAtUtc: string };
type Booking = { id: string; status: string; studentNote?: string; slot?: Slot };
const statusNames: Record<string, string> = { Pending: 'Ожидает подтверждения', Confirmed: 'Подтверждено', Completed: 'Завершено', Cancelled: 'Отменено', NoShow: 'Неявка' };
const dateTime = (value: string) => `${date(value)} · ${new Date(value).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}`;

export function TrainerCabinet() {
  const requests = useApi<Incoming[]>('/api/trainers/requests/incoming');
  const slots = useApi<Slot[]>('/api/schedule/slots/my');
  const bookings = useApi<Booking[]>('/api/schedule/bookings/trainer');
  const action = useAction(); const [start, setStart] = useState(''); const [end, setEnd] = useState(''); const [note, setNote] = useState('');
  const [confirmation, setConfirmation] = useState<{ title: string; url: string; body?: unknown }>();
  const reload = () => { requests.reload(); slots.reload(); bookings.reload(); };
  return <><Heading eyebrow="ВАШИ ЗАНЯТИЯ И УЧЕНИКИ" title="Кабинет тренера" /><Notice error={requests.error || slots.error || bookings.error} /><Notice {...action} />
    <div className="section-heading"><h2>Входящие заявки</h2></div><section className="card">{requests.loading ? <Loading /> : !requests.data?.length ? <Empty>Новых заявок пока нет.</Empty> : requests.data.map(request => <div className="list-row" key={request.id}><span><strong>{request.message || 'Новый ученик'}</strong><small>{date(request.createdAtUtc)} · {request.goal}</small></span><button className="primary" disabled={action.busy} onClick={() => action.run(async () => { await api(`/api/trainers/requests/${request.id}/accept`, 'POST'); reload(); }, 'Заявка принята')}>Принять</button><button className="secondary" onClick={() => setConfirmation({ title:'Отклонить заявку?', url:`/api/trainers/requests/${request.id}/decline`, body:{ reason:'Тренер пока не может принять заявку' } })}>Отклонить</button></div>)}</section>
    <div className="section-heading"><h2>Занятия</h2></div><section className="card">{bookings.loading ? <Loading /> : !bookings.data?.length ? <Empty><CalendarDays size={28} /><p>У вас пока нет записей.</p></Empty> : bookings.data.map(booking => <div className="booking-card" key={booking.id}><h3>{booking.slot ? dateTime(booking.slot.startUtc) : 'Занятие'}</h3><p className="muted">{statusNames[booking.status] ?? booking.status} · {booking.studentNote}</p><div className="form-actions">{booking.status === 'Pending' && <button className="primary" disabled={action.busy} onClick={() => action.run(async () => { await api(`/api/schedule/bookings/${booking.id}/confirm`, 'POST'); reload(); }, 'Запись подтверждена')}>Подтвердить</button>}{booking.status === 'Confirmed' && <><button className="primary" onClick={() => setConfirmation({ title:'Отметить занятие завершённым?', url:`/api/schedule/bookings/${booking.id}/complete` })}>Занятие проведено</button><button className="secondary" onClick={() => setConfirmation({ title:'Отметить неявку ученика?', url:`/api/schedule/bookings/${booking.id}/no-show` })}>Неявка</button></>}{['Pending','Confirmed'].includes(booking.status) && <button className="secondary" onClick={() => setConfirmation({ title:'Отменить занятие?', url:`/api/schedule/bookings/${booking.id}/cancel`, body:{ reason:'Отмена тренером' } })}>Отменить</button>}</div></div>)}</section>
    <div className="section-heading"><h2>Свободное время</h2></div><div className="profile-layout"><section className="card"><h3>Добавить время для записи</h3><form onSubmit={e => { e.preventDefault(); void action.run(async () => { await api('/api/schedule/slots', 'POST', { startUtc:new Date(start).toISOString(), endUtc:new Date(end).toISOString(), note }); setStart(''); setEnd(''); setNote(''); slots.reload(); }, 'Время добавлено в расписание'); }}><label>Начало<input type="datetime-local" required value={start} onChange={e => setStart(e.target.value)} /></label><label>Окончание<input type="datetime-local" required min={start} value={end} onChange={e => setEnd(e.target.value)} /></label><label>Примечание<input maxLength={500} placeholder="Например, зал на втором этаже" value={note} onChange={e => setNote(e.target.value)} /></label><button className="primary" disabled={action.busy}><Plus size={17} />Добавить</button></form></section><section className="card"><h3>Ближайшие 30 дней</h3>{slots.loading ? <Loading /> : !slots.data?.length ? <p className="muted">Добавьте доступное время слева.</p> : slots.data.map(slot => <div className="list-row" key={slot.id}><span><strong>{dateTime(slot.startUtc)}</strong><small>{slot.isBooked ? 'Занято' : 'Свободно'} · {slot.note}</small></span>{!slot.isBooked && <button className="secondary" disabled={action.busy} onClick={() => action.run(async () => { await api(`/api/schedule/slots/${slot.id}`, 'DELETE'); slots.reload(); }, 'Время удалено')}>Убрать</button>}</div>)}</section></div>
    {confirmation && <div className="dialog-backdrop"><section className="card dialog" role="alertdialog" aria-modal="true" aria-labelledby="trainer-action"><h2 id="trainer-action">{confirmation.title}</h2><p>Изменение статуса будет видно ученику.</p><div className="form-actions"><button className="secondary" onClick={() => setConfirmation(undefined)}>Назад</button><button className="primary" disabled={action.busy} onClick={() => action.run(async () => { await api(confirmation.url, 'POST', confirmation.body); setConfirmation(undefined); reload(); }, 'Статус обновлён')}>Подтвердить</button></div><Notice {...action} /></section></div>}
  </>;
}
